- name: Create ClamAV reports directory
  file:
    path: "{{user.home}}/.clamav"
    state: directory
  tags:
    - fast
    - clamav

- name: ClamAV scan for /home
  cron:
    name: Update ClamAV Virus DB
    special_time: "daily"
    # TODO: add --rm when confirmed to work
    job: "docker run -v clamav-db:/var/lib/clamav -v $HOME:/toscan:ro batmat/clamscan -i > {{user.home}}/.clamav/REPORT-HOME.$( date --iso-8601=minutes )"
  tags:
    - fast
    - cron
    - clamav

# TODO: scan the whole disk (excluding home, given already done above)
