- name: Create ClamAV reports directory
  file:
    path: "{{user.home}}/.clamav"
    state: directory
  tags:
    - fast
    - clamav

- name: ClamAV scan for /home
  cron:
    name: ClamAV scan for /home
    special_time: "daily"
    # TODO: add --rm when confirmed to work
    # TODO: likely, add CPU constraints too soon
    job: >
          docker run
          --name clamscan-home-$RANDOM
          -v clamav-db:/var/lib/clamav
          -v $HOME:/toscan:ro
          batmat/clamscan
          -iv
          --exclude-dir=/home/tiste/Photos
          --exclude-dir=/home/tiste/.m2/repository
          > {{user.home}}/.clamav/REPORT-HOME.$( date --iso-8601=minutes )
  tags:
    - fast
    - cron
    - clamav

- name: ClamAV scan for pix
  cron:
    name: ClamAV scan for pix
    special_time: "weekly"
    # TODO: add --rm when confirmed to work
    # TODO: likely, add CPU constraints too soon
    job: >
          docker run
          --name clamscan-pix-$RANDOM
          -v clamav-db:/var/lib/clamav
          -v $HOME/Photos:/toscan:ro batmat/clamscan
          -iv
          > {{user.home}}/.clamav/REPORT-PHOTOS.$( date --iso-8601=minutes )
  tags:
    - fast
    - cron
    - clamav

- name: ClamAV scan for .m2/repository
  cron:
    name: ClamAV scan for .m2/repository
    special_time: "daily"
    # TODO: add --rm when confirmed to work
    # TODO: likely, add CPU constraints too soon
    job: >
          docker run
          --name clamscan-m2repo-$RANDOM
          -v clamav-db:/var/lib/clamav
          -v $HOME/.m2/repository:/toscan:ro
          batmat/clamscan
          -iv
          --exclude-dir=/home/tiste/Photos
          --exclude-dir=/home/tiste/.m2/repository
          > {{user.home}}/.clamav/REPORT-HOME.$( date --iso-8601=minutes )
  tags:
    - fast
    - cron
    - clamav

- name: ClamAV scan for /
  cron:
    name: ClamAV scan for /
    special_time: "weekly"
    # TODO: add --rm when confirmed to work
    # TODO: likely, add CPU constraints too soon
    job: >
          docker run
          --name clamscan-root-$RANDOM
          -v clamav-db:/var/lib/clamav
          -v /:/toscan:ro batmat/clamscan
          -iv
          --exclude-dir=/home/tiste/
          > {{user.home}}/.clamav/REPORT-ROOT.$( date --iso-8601=minutes )
  tags:
    - fast
    - cron
    - clamav
