---
- hosts: 127.0.0.1
  connection: local
  roles:
    - { role: _base }
    - { role: personal }
    - { role: atom }
    - { role: docker }
    - { role: git }
    - { role: java }
    - { role: golang }
    - { role: gohugo }
    - { role: tmux }
    - { role: vagrant }
    - { role: sublime }
    - { role: maven }
    - { role: powerline }

  tasks:

    - name: Install personal packages
      become: yes
      dnf: name={{ item }} state=present
      with_items:
      - grisbi
      - keepass
      - gimp
      - ImageMagick
      - baobab
      - audacity
      - vlc
      - kphotoalbum
      - fdupes
      - ffmpegthumbs
      - kde-partitionmanager
      - jq
      - moreutils
