#!/bin/bash

currentDir=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )
ansible-playbook -i $currentDir/hosts --vault-password-file=$currentDir/.vault-password $currentDir/playbook.yml -e resetenv_path=$currentDir $@
