- include_vars: common-vars.yml
  tags: fast

- name: Check that the current machine is a Fedora 22
  assert: { that: "ansible_distribution == 'Fedora' and ansible_distribution_version == '22'" }

###############################################################################################
# Checking if currently at work to set the variable
#
- name: at work ?
  shell: "ping -c1 -i 0.2 mipih.net"
  register: i_am_at_work
  ignore_errors: yes
  changed_when: false
  tags: fast

- name: check if I'm at work
  set_fact: at_work={{ true if i_am_at_work.rc == 0 else false }}
  tags: fast

- debug: var=at_work

- include_vars: work-vars.yml.vault
  when: at_work == true
  tags: fast

###############################################################################################
# dnf configuration
#
- name: add dnf conf file
  template: src=dnf.conf owner=root group=root dest=/etc/dnf/dnf.conf mode=644
  tags: fast
  sudo: yes

###############################################################################################
# install packages
#
- { include: get-and-cache.yml, toget: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-22.noarch.rpm" }

- name: Install RPMFusion free repository
  sudo: yes
  dnf: name="{{ cached }}" state=present

- { include: get-and-cache.yml, toget: "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-22.noarch.rpm" }

- name: Install RPMFusion non-free repository
  sudo: yes
  dnf: name="{{ cached }}" state=present

- name: install packages
  sudo: yes
  dnf: name={{ item }} state=present
  with_items:
   - zsh
   - vim
   - tree
   - unzip
   - ntpdate

###############################################################################################
# tools settings
#
- name: set default shell to zsh
  sudo: yes
  user: name={{ user.name }} shell=/usr/bin/zsh state=present

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest={{ user.home }}/.oh-my-zsh
  environment: proxy_env

- name: add zshrc file
  template: src=zshrc owner={{ user.name }} group={{ user.name }} dest={{ user.home }}/.zshrc mode=644
  tags: fast

- name: init zshrc chunks directory
  file: path={{ user.home }}/.zshrc-chunks state=directory
  tags: fast

- name: add vimrc file
  template: src=vimrc owner={{ user.name }} group={{ user.name }} dest={{ user.home }}/.vimrc mode=644
  tags: fast
