- include_vars: common-vars.yml.vault
  tags: fast

- name: Check that the current machine is a Fedora 22
  assert: { that: "ansible_distribution == 'Fedora' and ansible_distribution_version == '22'" }

###############################################################################################
# Work part
#
- name: at work ?
  shell: "ping -c1 -i 0.2 {{ proxy.host }}"
  register: i_am_at_work
  ignore_errors: yes
  changed_when: false
  tags: fast

- name: check if I'm at work
  set_fact: at_work={{ true if i_am_at_work.rc == 0 else false }}
  tags: fast

- debug: var=at_work

- include_vars: work-vars.yml.vault
  when: at_work == true
  tags: fast

###############################################################################################
# dnf configuration
#
- name: add dnf conf file
  template: src=dnf.conf owner=root group=root dest=/etc/dnf/dnf.conf mode=644
  tags: fast
  sudo: yes

###############################################################################################
# install packages
#

- name: Install RPMFusion free repository
  sudo: yes
  dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-22.noarch.rpm state=present
  environment: proxy_env

- name: Install RPMFusion non-free repository
  sudo: yes
  dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-22.noarch.rpm state=present
  environment: proxy_env

- name: install packages
  sudo: yes
  dnf: name={{ item }} state=installed
  with_items:
   - zsh
   - docker
   - git
   - git-svn
   - git-gui
   - subversion
   - tree
   - unzip
   - vim
   - vagrant  
   - vagrant-libvirt
   - VirtualBox
   - kernel-devel
   - golang
   - java-1.8.0-openjdk-devel
   - groovy
   - ntpdate
   - rubygem-asciidoctor
   # Personal
   - kphotoalbum
   - grisbi
   - keepass
   - gimp
   - ImageMagick
   - baobab
   - audacity
   - vlc
   - ffmpegthumbs
   - kde-partitionmanager
###############################################################################################
# ssh configuration
#
- include_vars: sshconfig.yml.vault

- name: remove current ssh config file
  file:
      path="{{ user.home }}/.ssh/config"
      state=absent
  changed_when: false

- name: generate ~/.ssh/config
  lineinfile:
      dest="{{ user.home }}/.ssh/config"
      line="{{ item.value }}"
      state=present
      insertafter=EOF
      create=yes
      owner="{{ user.name }}"
      group="{{ user.name }}"
      mode=0700
  with_dict: sshconfig.hosts
  changed_when: false

- name: Set Git autosquash true globally (todo => idempotentize)
  shell: git config --global rebase.autosquash true

###############################################################################################
# tools settings
#

- name: Clone JEnv
  git: repo=https://github.com/gcuisinier/jenv.git  dest="{{ user.home }}/.jenv"
  environment: proxy_env

- name: configure git
  shell: >
     git config --global user.email '{{ user.email }}' &&
     git config --global user.name '{{ user.fullName }}'
  changed_when: false
  tags: fast

- name: set default shell to zsh
  sudo: yes
  user: name={{ user.name }} shell=/usr/bin/zsh state=present

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest={{ user.home }}/.oh-my-zsh
  environment: proxy_env

- name: add zshrc file
  template: src=zshrc owner={{ user.name }} group={{ user.name }} dest={{ user.home }}/.zshrc mode=644
  tags: fast

- name: Get Sublime Text 3
  get_url: url="http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3083_x64.tar.bz2" dest=/tmp/sublime_text_3_build_3083_x64.tar.bz2
  environment: proxy_env

- name: Uncompress Sublime under the .tools directory
  unarchive: src=/tmp/sublime_text_3_build_3083_x64.tar.bz2 dest="{{ user.home }}/.tools/"

- name: SublimeText3 configuration
  template: src=sublime-text-eclipse-style owner={{ user.name }} group={{ user.name }} dest="{{ user.home }}/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap" mode=664
  tags: fast

- name: Download Atom Text Editor
  get_url: url=http://atom.io/download/rpm dest=/tmp/atom.rpm
  environment: proxy_env
  tags: atom

- name: Install Atom Text Editor
  sudo: yes
  dnf: name=/tmp/atom.rpm state=present
  tags: atom

- name: Install Atom Asciidoctor Preview package
  shell: apm install asciidoc-preview
  environment: proxy_env

- name: Install Atom Asciidoctor Eclipse Keybindings package
  shell: apm install eclipse-keybindings
  environment: proxy_env

###############################################################################################
# Maven

- name: Make sure .m2 directory exists
  file: path="{{ ansible_env.HOME }}/.m2" state=directory mode=0755

- name: Setting up corporate Maven Settings
  template: src=mavensettings.xml dest={{ ansible_env.HOME }}/.m2/settings.xml

###############################################################################################
# Docker
#
- name: Docker config file
  template: src=docker-config owner=root group=root dest=/etc/sysconfig/docker
  sudo: yes
  notify:
   - restart docker
  tags: fast

- name: start and configure Docker
  service: name=docker state=started
  sudo: yes
  tags: fast

- service: name=docker enabled=true

- name: Install Docker machine
  sudo: yes
  get_url: url=https://github.com/docker/machine/releases/download/v0.3.0/docker-machine_linux-amd64 dest=/usr/local/bin/docker-machine
  environment: proxy_env

- name: Make Docker Machine executable
  sudo: yes
  file: path=/usr/local/bin/docker-machine state=file mode="u+rx,a+x,g+x"

###############################################################################################
# VirtualBox
#

# Installing the typical 'kmod-VirtualBox' package through dnf won't work because it has to be
# aligned/republished with the latest kernel and it rarely is.
- name: Configure kernel module for VirtualBox
  sudo: yes
  shell:  'akmods --kernel $( uname -r )'
  tags: VirtualBox

- name: Configure kernel module for VirtualBox
  sudo: yes
  shell: systemctl restart systemd-modules-load.service
  tags: VirtualBox
