- name: install packages
  become: yes
  dnf: name={{ item }} state=present
  with_items:
   - vagrant
   - VirtualBox-5.0 # not compulsory for vagrant, but far better indeed

###############################################################################################
# VirtualBox specifics (create a dedicated VB role, todo?)
#

# Installing the typical 'kmod-VirtualBox' package through dnf won't work because
# it must be aligned/republished with the latest kernel and rarely is.

# TODO : /idempotentize/


- name: add zshrc chunk
  template: src=zshrc-vagrant dest="{{ user.home }}/.zshrc-chunks/vagrant"
  tags: fast
