---
# Things unlikely to be of interest for anyone else than me :-)

- name: Add zshrc chunk
  copy: src=zshrc-personal dest="{{ user.home }}/.zshrc-chunks/perso"
  tags: fast

- name: Set wheel group sudoers without password
  become: yes
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  tags: fast

- name: Configure Login Manager (logind.conf)
  become: yes
  copy: src=logind.conf dest=/etc/systemd/logind.conf
  tags:
    - fast
    - bim

- name: Install personal packages
  become: yes
  dnf: name={{ item }} state=present
  tags: pouet
  with_items:
    - grisbi
    - keepass
    - gimp
    - ImageMagick
    - baobab
    - audacity
    - vlc
    - kphotoalbum
    - fdupes
    - kde-partitionmanager
    - jq
    - moreutils
    - NetworkManager
    - lxrandr # useful complement to xrandr to quickly set up screen for prez
    - pavucontrol
    - dropbox # todo : dedicated role

- name: cache useful images
  become: yes
  shell: docker pull {{ item }}
  with_items:
    - batmat/asciidoctor-prez
    - batmat/process-media
    - batmat/rotate-video
    - pashi/garmin-antfs
    - busybox
    - alpine
    - swarm
    - jenkinsci/jenkins:latest
    - jenkins:1.651.3 # go to 2.7.1 when published
    - debian
    - fedora:23
    - centos:7
  register: result
  changed_when: "'Status: Image is up to date for' not in result.stdout"
  tags:
    - docker
    - dockercache

- name: Create custom scripts directory
  file: name="{{ user.home }}/.bin" state=directory
  tags:
    - perso
    - fast

- name: Copy custom scripts
  copy: src="{{item}}" dest="{{ user.home }}/.bin/{{ item }}" mode="u+rx"
  with_items:
    - "xrandr-double-screen.sh"
    - "xrandr-reset-LVDS.sh"
  tags:
    - perso
    - fast
