---
# Things unlikely to be of interest for anyone else than me :-)

- name: Add zshrc chunk
  copy: src=zshrc-personal dest="{{ user.home }}/.zshrc-chunks/perso"
  tags: fast

- name: Set wheel group sudoers without password
  become: yes
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  tags: fast

- name: Configure Login Manager (logind.conf)
  become: yes
  copy: src=logind.conf dest=/etc/systemd/logind.conf
  tags:
    - fast
    - bim
- name: Make sure some packages are absent
  become: yes
  dnf: name={{ item }} state=absent
  with_items:
    - blueman # deprecated/superseded by blueberry

- name: Install personal packages
  become: yes
  dnf: name={{ item }} state=present
  with_items:
    - grisbi
    - keepass
    - gimp
    - ImageMagick
    - baobab
    - audacity
    - vlc
    - kphotoalbum
    - fdupes
    - kde-partitionmanager
    - jq
    - moreutils
    - NetworkManager
    - lxrandr # useful GUI complement to xrandr to quickly set up screen for prez
    - pavucontrol
    - recordmydesktop
    - ffmpeg
    - p7zip
    - p7zip-gui
    - unrtf
    - wireshark
    - ShellCheck
    - xmlstarlet
    - redis
    - git-extras
    - lm_sensors
    - blueberry
    - meld
    - iotop
    - java-1.8.0-openjdk-src # move into Java role?
    - trickle # https://askubuntu.com/a/181411 bandwidth limiting (cool to test flakiness issues related to network)

- name: cache useful images
  become: yes
  shell: docker pull {{ item }}
  with_items:
    - batmat/process-media
    - batmat/rotate-video
    - pashi/garmin-antfs
    - busybox
    - alpine
    - jenkins/jenkins:latest
    - jenkins/jenkins:lts
    - debian:latest
    - fedora:28
    - fedora:latest
    - centos:latest
    #work
  register: result
  changed_when: "'Status: Image is up to date for' not in result.stdout"
  tags:
    - dockercache

- name: Create custom scripts directory
  file: name="{{ user.home }}/.bin" state=directory
  tags:
    - perso
    - fast

- name: Copy custom scripts
  copy: src="{{item}}" dest="{{ user.home }}/.bin/{{ item }}" mode="u+rx"
  with_items:
    - "xrandr-double-screen.sh"
    - "xrandr-reset-LVDS.sh"
    - "brightnessctl"
    - "change-background"
    - "searchdeadlock"
    - "power-alert.sh"
    - "check-commands-running.sh"
    - "toggle-crashplan"
    - "gclone.sh"
    - "limit-bandwidth"
  tags:
    - perso
    - fast
    - cron

- name: Install crontab checks
  cron:
    name:   "{{ item.name }}"
    minute: "{{ item.minute }}"
    job:    "{{ user.home }}/.bin/{{ item.job }} >/dev/null"
  with_items:
  - { name: 'Alert if battery is too low',                   minute: '*/3', job: 'power-alert.sh' }
  - { name: 'Check processes expected to be always running', minute: '*/4', job: 'check-commands-running.sh' }
  - { name: 'Reset screen if only main one is plugged in',   minute: '*/2', job: 'xrandr-reset-LVDS.sh' }
  tags:
    - fast
    - cron
