---
# Things unlikely to be of interest for anyone else than me :-)

- name: Add zshrc chunk
  copy: src=zshrc-personal dest="{{ user.home }}/.zshrc-chunks/perso"
  tags: fast

- name: Set wheel group sudoers without password
  become: yes
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  tags: fast

- name: Configure Login Manager (logind.conf)
  become: yes
  copy: src=logind.conf dest=/etc/systemd/logind.conf
  tags:
    - fast
    - bim

- name: Install personal packages
  become: yes
  dnf: name={{ item }} state=present
  with_items:
    - grisbi
    - keepass
    - gimp
    - ImageMagick
    - baobab
    - audacity
    - vlc
    - kphotoalbum
    - fdupes
    - kde-partitionmanager
    - jq
    - moreutils
    - NetworkManager
    - lxrandr # useful complement to xrandr to quickly set up screen for prez
    - pavucontrol
    - recordmydesktop
    - ffmpeg
    - p7zip
    - p7zip-gui
    - unrtf
    - wireshark
    - ShellCheck
    - xmlstarlet
    - redis
    - git-extras
    - lm_sensors
    - blueman
    - meld

- name: cache useful images
  become: yes
  shell: docker pull {{ item }}
  with_items:
    - batmat/process-media
    - batmat/rotate-video
    - pashi/garmin-antfs
    - busybox
    - alpine
    - jenkinsci/jenkins:latest
    - jenkins:2.60.1
    - jenkins:2.60.1-alpine
    - jenkins:latest # in case a new one has been published
    - jenkins:alpine # in case a new one has been published
    - debian
    - fedora:25
    - fedora:latest
    - centos:7
    #work
    - cloudbees/jenkins-enterprise:latest
    - cloudbees/jenkins-operations-center:latest
  register: result
  changed_when: "'Status: Image is up to date for' not in result.stdout"
  tags:
    - docker
    - dockercache

- name: Create custom scripts directory
  file: name="{{ user.home }}/.bin" state=directory
  tags:
    - perso
    - fast

- name: Copy custom scripts
  copy: src="{{item}}" dest="{{ user.home }}/.bin/{{ item }}" mode="u+rx"
  with_items:
    - "xrandr-double-screen.sh"
    - "xrandr-reset-LVDS.sh"
    - "brightnessctl"
    - "change-background"
    - "searchdeadlock"
    - "power-alert.sh"
    - "check-commands-running.sh"
  tags:
    - perso
    - fast

- name: check battery and alert if too low (sometimes, I miss the status bar)
  cron:
    name: Alert if battery is too low
    minute: "*"
    job: "/home/tiste/.bin/power-alert.sh"
  tags:
    - fast
    - cron

- name: check processes expected to be always running
  cron:
    name: Check processes expected to be always running
    minute: "*"
    job: "/home/tiste/.bin/check-commands-running.sh"
  tags:
    - fast
    - cron
