---

- name: Install aws-cli
  become: yes
  environment: "{{proxy_env}}"
  pip: name=awscli state=absent
  tags: awscli

- name: Install awscli package
  become: yes
  dnf: name="awscli" state=present
  tags: awscli
