- name: install packages
  sudo: yes
  dnf: name={{ item }} state=present
  with_items:
   - git
   - git-svn
   - git-gui
   - tig

- name: configure git
  shell: >
     git config --global user.email '{{ user.email }}' &&
     git config --global user.name '{{ user.fullName }}'
  changed_when: false
  tags: fast

- name: add zshrc chunk
  template: src=zshrc-git dest="{{ user.home }}/.zshrc-chunks/git"
  tags: fast
