- name: install packages
  become: yes
  dnf: name={{ item }} state=present
  with_items:
   - git
   - git-svn
   - git-gui
   - aspell-fr # for git gui typo checking
   - tig

- name: configure global git config
  template: src=global-gitconfig dest="{{ user.home }}/.gitconfig"
  tags: fast

- name: copy Git commit message template
  template: src=commit-template dest="{{ user.home }}/.git_commit_template"
  tags: fast

- name: add zshrc chunk
  template: src=zshrc-git dest="{{ user.home }}/.zshrc-chunks/git"
  tags: fast


##############
# GitHub CLI
##############
- import_tasks: get-and-cache.yml
  vars:
    toget: "https://github.com/github/hub/releases/download/v2.3.0-pre9/hub-linux-amd64-2.3.0-pre9.tgz"
  tags: github

- name: Check GitHub CLI install dir is present
  become: yes
  file: path=/opt/hub state=directory
  tags: github

# TODO : not idempotent
- name: Install GitHub CLI
  become: yes
  shell: tar xvzf {{ cached }} --strip 1 -C /opt/hub
  tags: github

- name: Install GitHub CLI zsh completion
  get_url:
    url: "https://raw.githubusercontent.com/github/hub/master/etc/hub.zsh_completion"
    dest: "{{ user.home }}/.zshrc-chunks/_git_hub_zsh_completion"
  tags: github
