---

- name: Install Atom RPM key
  become: yes
  rpm_key:
    state: present
    key: https://packagecloud.io/AtomEditor/atom/gpgkey

- name: Add Atom repository
  become: yes
  yum_repository:
    name: atom
    description: Atom YUM repo
    baseurl: "https://packagecloud.io/AtomEditor/atom/el/7/$basearch/"
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    enabled: yes
    gpgcheck: no
  tags:
    - atom

- name: Install Atom Text Editor
  become: yes
  dnf: name=atom state=present
  tags: atom

- name: Configure the proxy for atom
  template: src=apmrc dest="{{ user.home }}/.atom/.apmrc"
  tags:
    - atom
    - fast
    - proxy

# Without that, one can have a Warning:
# "Unable to watch path: config.cson. Make sure you have permissions to ~/.atom/config.cson.
# On linux there are currently problems with watch sizes. See this document for more info."
# https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path
- name: Put higher number for fs.inotify.max_user_watches
  become: yes
  lineinfile: dest=/etc/sysctl.conf line="fs.inotify.max_user_watches = 3000000" insertafter=EOF
  tags:
    - atom
    - fast

- name: Install Atom Asciidoctor Packages
  shell: apm install {{ item }}
  environment: "{{proxy_env}}"
  changed_when: false
  with_items:
    - eclipse-keybindings
    - asciidoc-preview
    - language-groovy
    - language-docker
    - file-icons
    - language-ansible
    - minimap
    - go-plus
    - vim-modeline
  tags: atom

- name: Set Atom Preferences
  copy: src=atom-config.cson dest="{{ user.home }}/.atom/config.cson"
  tags: fast

- name: add zshrc atom chunk
  template: src=zshrc-atom dest="{{ user.home }}/.zshrc-chunks/atom"
  tags: fast
