- { include: get-and-cache.yml, toget: "https://atom.io/download/rpm" }

- name: Install Atom Text Editor
  become: yes
  dnf: name="{{ cached }}" state=present
  tags: atom

- name: Configure the proxy for atom
  template: src=apmrc dest="{{ user.home }}/.atom/.apmrc"
  tags:
    - atom
    - fast
    - proxy

- name: Install Atom Asciidoctor Packages
  shell: apm install {{ item }}
  environment: proxy_env
  changed_when: false
  with_items:
    - eclipse-keybindings
    - asciidoc-preview
    - language-groovy
    - language-docker
    - file-icons
    - language-ansible
  tags: atom

- name: Set Atom Preferences
  copy: src=atom-config.cson dest="{{ user.home }}/.atom/config.cson"
  tags: fast

- name: add zshrc atom chunk
  template: src=zshrc-atom dest="{{ user.home }}/.zshrc-chunks/atom"
  tags: fast
