- { include: get-and-cache.yml, toget: "http://atom.io/download/rpm" }

- name: Install Atom Text Editor
  sudo: yes
  dnf: name="{{ cached }}" state=present
  tags: atom

- name: Configure the proxy for atom
  template: src=apmrc dest="{{ user.home }}/.atom/.apmrc"
  tags:
    - atom
    - fast

- name: Install Atom Asciidoctor Preview package
  shell: apm install asciidoc-preview
  environment: proxy_env
  changed_when: false

- name: Install Atom Asciidoctor Eclipse Keybindings package
  shell: apm install eclipse-keybindings
  environment: proxy_env
  changed_when: false

- name: Set Atom Preferences
  copy: src=atom-config.cson dest="{{ user.home }}/.atom/config.cson"
  tags: fast

- name: add zshrc atom chunk
  template: src=zshrc-atom dest="{{ user.home }}/.zshrc-chunks/atom"
  tags: fast
