---
- name: install packages
  become: yes
  dnf: name={{ item }} state=present
  with_items:
   - java-1.8.0-openjdk-devel
   - groovy

- name: Clone JEnv
  git: repo=https://github.com/gcuisinier/jenv.git  dest="{{ user.home }}/.jenv"
  environment: "{{proxy_env}}"

- name: add zshrc chunk
  template: src=zshrc-java dest="{{ user.home }}/.zshrc-chunks/java"
  tags: fast
