#!/bin/bash

set -euo pipefail

BRIGHTNESS=/sys/class/backlight/intel_backlight/brightness
MAX=/sys/class/backlight/intel_backlight/max_brightness
ACTUAL=/sys/class/backlight/intel_backlight/actual_brightness

STEP=80
MIN=1

if [[ "$#" -ne 1 ]]; then
    echo "Illegal number of parameters"
    exit 1
fi

if [[ ( $1 != '+' && $1 != '-' ) ]]; then
    echo "Niiiii"
    exit 2
fi

echo "Current value: $(cat $ACTUAL), asked=$1"

function set_brightness() {
  value=$1
  if [[ $1 -gt $(cat $MAX) ]]; then
      value=$(cat $MAX)
  elif [[ $1 -lt $MIN ]]; then
      echo "trop petit $1 < $MIN"
      value=$MIN
  fi
  echo "Setting new value => $value"
  echo $value | sudo tee /sys/class/backlight/intel_backlight/brightness
}


if [[ $1 == '+' ]]; then
    echo "moar brightness"
    newValue=$(( $(cat $ACTUAL) + $STEP ))

    set_brightness $newValue
fi

if [[ $1 == '-' ]]; then
    echo "less brightness"
    newValue=$(( $(cat $ACTUAL) - $STEP ))

    set_brightness $newValue
fi
