#!/bin/bash

set -euo pipefail

OPTIONS="--bg-max"
if [[ $# != 0 && "A$1A" != "AA" ]] ; then
  photo="$1"
else
  PHOTOS_DIR=$HOME/Dropbox/perso/backgrounds
  photo=$(find $PHOTOS_DIR -type f -name "*JPG" -or -name "*.jpg" | shuf -n 1)
fi

isPortrait=$(( $( identify -format '%h %w' "$photo" | tr ' ' '-' ) > 0 ))
if [[ $isPortrait == 1 ]] ; then
  OPTIONS=--bg-max
else
  OPTIONS=--bg-fill
fi
echo "switching to $photo"
feh $OPTIONS "$photo"
