- name: install packages
  sudo: yes
  dnf: name={{ item }} state=present
  with_items:
   - tmux
   - tmuxinator

- name: add tmuxinator-completion file for zsh
  copy: src=tmuxinator-completion.zsh owner={{ user.name }} group={{ user.name }} dest={{ user.home }}/.tmuxinator-completion.zsh mode=644
  tags: fast

- name: create tmuxinator config directories
  file: path={{ user.home }}/.tmuxinator owner={{ user.name }} group={{ user.name }} state=directory
  tags: fast

- name: add tmuxinator config file
  template: src=tmuxinator/work.yml owner={{ user.name }} group={{ user.name }} dest={{ user.home }}/.tmuxinator/work.yml
  tags: fast

- name: add zshrc chunk
  template: src=zshrc-tmux dest="{{ user.home }}/.zshrc-chunks/tmux"
  tags: fast
