ZSH=$HOME/.oh-my-zsh
ZSH_THEME="geoffgarside"

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
autoload -Uz compinit
compinit
COMPLETION_WAITING_DOTS="true"

plugins=(git history-substring-search docker mvn lol)
source $ZSH/oh-my-zsh.sh

export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# some git aliases from zsh git plugin are provided, I prefer to customize them entirely
unalias -m "*"

alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..

alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'

alias vi="vim"

alias get='sudo dnf install'
alias search='sudo dnf search'

alias h='history'
alias c='clear'

alias d='docker'
alias dl='docker ps -l -q'
alias dclean='docker rm $(docker ps -a -q)'
alias dm='docker-machine'

alias gs='git status'
alias gwip='git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m "--wip--"'
alias gpr='git pull --rebase'
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'

alias lb='mvn clean install -DskipTests -Dinvoker.skip=true'

alias resetenv='{{ resetenv_path }}/resetenv'
alias r=resetenv

export PATH=~/.tools/sublime_text_3:$PATH
alias s='sublime_text'
alias sub='sublime_text'
alias a='atom'

export GOPATH={{ user.home }}/workspace-go

export JAVA_HOME=/usr/lib/jvm/java-1.8.0
export PATH=$JAVA_HOME/bin:$PATH

# JEnv config -- see http://www.jenv.be/
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

{% if at_work == true %}
export MODE='MiPih'
export http_proxy='{{ proxy_env.http_proxy }}'
export https_proxy='{{ proxy_env.https_proxy }}'
export no_proxy='{{ proxy_env.no_proxy }}'
{% else %}
export MODE='HOME'
{% endif %}

export PS1="[$MODE] $PS1"

unsetproxy() {
	unset http_proxy
	unset https_proxy
}

if [ -f ~/.myzhrc ]; then
  source ~/.myzhrc
fi
