ZSH=$HOME/.oh-my-zsh
ZSH_THEME="geoffgarside"

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
autoload -Uz compinit
compinit
COMPLETION_WAITING_DOTS="true"

plugins=(git history-substring-search docker docker-compose vagrant mvn lol)
source $ZSH/oh-my-zsh.sh

export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# some git aliases from zsh git plugin are provided, I prefer to customize them entirely
unalias -m "*"

alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..

alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'
alias l=ls

alias vi="vim"

alias get='sudo dnf install'
alias search='sudo dnf search'

alias h='history'
alias c='clear'

alias t='tmux'
alias tls="tmux ls"
alias ta="tmux a -t"
alias tk="tmux kill-session -t"

source {{ user.home }}/.tmuxinator-completion.zsh

alias d='docker'
alias dl='docker ps -l -q'
alias dm='docker-machine'
alias dc='docker-compose'
alias swarm='docker run --rm swarm'
alias dclean-all-containers='docker rm $(docker ps -a -q)'
alias dclean-old-containers="docker ps -a | grep Exited | grep 'days ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm"
alias cco=dclean-old-containers
alias dclean-dangling-images='docker rmi $(docker images --filter dangling=true --quiet)'

# Should be the default, but unexpectedly tries to use libvirt on my machine
export VAGRANT_DEFAULT_PROVIDER=virtualbox

#Buggy KDE5 Plasmashell, to restart easily
alias kp='killall plasmashell ; nohup plasmashell >/dev/null&'

function docker_clean_orphan_volumes() {
 	docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes $@
}
alias dclean-orphan-volumes=docker_clean_orphan_volumes

export EDITOR=vim
alias gs='git status'
alias gwip='git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m "--wip--"'
alias gpr='git pull --rebase'
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'

alias lb='mvn clean install -DskipTests -Dinvoker.skip=true'

function httpie_docker() {
	docker run -it --rm --net=host clue/httpie $@
}	
alias http=httpie_docker

function resetenv() {
	{{ resetenv_path }}/resetenv $@
	source $HOME/.zshrc
}
alias r=resetenv

export PATH={{ tools.path }}/sublime_text_3:$PATH
alias s='sublime_text'
alias sub='sublime_text'
alias a='atom'

export GOPATH={{ user.home }}/workspace-go

export JAVA_HOME=/usr/lib/jvm/java-1.8.0
export PATH=$JAVA_HOME/bin:$PATH

# JEnv config -- see http://www.jenv.be/
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

{% if at_work == true %}
export MODE='MiPih'
export http_proxy='{{ proxy_env.http_proxy }}'
export https_proxy='{{ proxy_env.https_proxy }}'
export no_proxy='{{ proxy_env.no_proxy }}'
{% else %}
export MODE='HOME'
{% endif %}

export PS1="[$MODE] $PS1"

unsetproxy() {
	unset http_proxy
	unset https_proxy
}

if [ -f ~/.myzhrc ]; then
  source ~/.myzhrc
fi
