- name: Check possibly conflicting docker packages are *not* installed
  dnf: name={{ item }} state=absent
  with_items:
    - docker
    - docker.io
  tags: fast

- name: Add Official Docker RPM repository
  become: yes
  shell: dnf config-manager --add-repo http://yum.dockerproject.org/repo/main/fedora/23
  args:
    creates: /etc/yum.repos.d/yum.dockerproject.org_repo_main_fedora_23.repo
  tags: fast

- name: Add gpg key for Docker repo
  become: yes
  lineinfile:
    dest: /etc/yum.repos.d/yum.dockerproject.org_repo_main_fedora_23.repo
    line: gpgkey=https://yum.dockerproject.org/gpg
    state: present
  tags: fast

- name: Install Docker Package from Docker Inc
  become: yes
  dnf: name=docker-engine state=present

- name: Create a docker group
  become: yes
  group: name=docker state=present
  tags: fast

- name: Add the current user to the docker group
  become: yes
  user: name="{{ user.name }}" groups=docker append=yes
  tags: fast

- name: Docker systemd configuration
  become: yes
  template: src=docker-systemd-config owner=root group=root dest=/usr/lib/systemd/system/docker.service
  notify:
   - restart docker
  tags:
    - fast
    - proxy

- name: Docker config file
  become: yes
  template: src=docker-sysconfig owner=root group=root dest=/etc/sysconfig/docker
  notify:
   - restart docker
  tags:
    - fast
    - proxy

- name: start and configure Docker
  service: name=docker state=started
  become: yes
  tags: fast

- { include: get-and-cache.yml, toget: "https://github.com/docker/machine/releases/download/v0.5.2/docker-machine_linux-amd64.zip" }

- name: Install Docker machine *
  become: yes
  unarchive: src="{{ cached }}" dest=/usr/local/bin

- name: Make Docker Machine executable
  become: yes
  file: path=/usr/local/bin/docker-machine state=file mode="u+rx,a+x,g+x"

- { include: get-and-cache.yml, toget: "https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Linux-x86_64" }

- name: Install Docker Compose
  become: yes
  copy: src="{{ cached }}" dest=/usr/local/bin/docker-compose

- name: Make Docker compose executable
  become: yes
  file: path=/usr/local/bin/docker-compose state=file mode="u+rx,a+x,g+x"

- name: check inodes usage and notify UI if below threshold
  cron:
    name: check inodes usage for /var/lib/docker
    minute: "*"
    job: "DISPLAY=:0 export INODES_LEFT=$( df --output=iavail /var/lib/docker | tail -1 ) ; /bin/bash -c \"if [ $INODES_LEFT -lt 200000 ]; then notify-send -t 2000 'WARNING: INODES NUMBER < 200k' 'Only $INODES_LEFT inodes left' ; fi\""
  tags:
    - fast
    - cron

- name: add zshrc docker chunk
  template: src=zshrc-docker dest="{{ user.home }}/.zshrc-chunks/docker"
  tags: fast
